### ISSUE TITLE
Cannot find name 'require'

### ISSUE THREAD

**Issue by kevinsalerno** [joshterrill/app-version#1]
Does not work with Ionic 3 + Angular 5 + typescript 2.4.2

**Comment by UniK** [comment]
@kevinsalerno 
Try to add `"node"` to the `compilerOptions.types` array in the `tsconfig.app.ts` file. 
```ts
/* tsconfig.app.ts */
{
  ...
  "compilerOptions": {
    "types": ["node"] 
  }
}
```

**Comment by kevinsalerno** [comment]
I think I tried that before finding this solution:
`declare function require(name: string);
`

then simply
`
  version = require("../../../package.json").version;  
`
